#+title: Government cruelty and criminality
:PROPERTIES:
:ID:       edca1634-22d3-43bc-afa4-24f49afaa4e6
:END:

* Mídia NINJA  December 21, 2016  ·
VERGONHA!

Por 30 votos a 23, a Assembleia Legislativa gaúcha decidiu durante a
madrugada pela extinção de oito fundações do Estado. O desrespeito às
instituições históricas e à carreira de mais de mil funcionários
concursados, que serão demitidos às vésperas do Natal, reverberou na
comemoração dos deputados da base do governador Sartori (PMDB).

Do lado de fora, barrados pela Brigada Militar, dezenas de
funcionários choravam por milhões de gaúchos. Eles acompanharam mais
de 14 horas de sessão ao longo de um dia marcado pela repressão
policial e debates intensos.

O projeto aprovado aniquila as Fundações Piratini (administradora das
emissoras públicas TVE e FM Cultura), a Fundação de Economia e
Estatística (FEE), a Metroplan, a Cientec, a FDRH, a Fepagro e a
Fundação Gaúcha de Tradição e Folclore. Deputados da oposição e
especialistas criticam a falta de diálogo e de estudos para embasar a
medida, cujo impacto nas finanças do Estado é irrelevante.

O pacote de maldades do Governo Sartori ataca diretamente a
inteligência do Rio Grande do Sul e sua capacidade de gerar
conhecimento, conduzir pesquisas, embasar novas políticas públicas,
democraticar a comunicação e fomentar a cultura local.

A votação de outras medidas de arrocho e entrega do patrimônio público
continua nesta quarta-feira.

