#+title: Relativism's Remedy
- tags :: Relativism. [[file:20210629130244-ant_and_the_grasshopper.org][Ant and the Grasshopper]]. 
  
In Brazil, Relativism is a common philosophy in practice. Yeah, people want more to be right, than effective. When, the scientific method says, forget being right; model reality to actual physical data.

But, let people be, I guess. These things can be solved through generation's natural selection. I do my part of not having pity, nor helping people who victimize themselves - at the same time, refuses to school themselves; give primacy to watching television over reading books, articles, or even having meaningful conversations.

When they knock on my door, and they frequently do, I say there is no bread.

People wanna have kids, on a world frequently more complex and saturated, for example. I CHOOSE not to. If you mock me for my choice, then you get poor, unable to maintain your family, then - in this remote future - you come to me begging because I have surplus... Well, good luck! That's all I have to you. Nock another door.

But, note, that's an old passage, the Ant and the Grasshopper. Although, It is as valid then, as it is now.

People are inconsequential on their life views and attitudes. And, the best you do to move past that is to let people screw themselves with their broken world view. At the same time, exercising the ability of saying "No", instead of the kind "I told you; come here, I will fix your problems, yet again".
