#+title: Masters and Sufficiency
#+filetags: :Mastery:Path:Freedom:Learning:Pupil:Master:Reflection:
:PROPERTIES:
:ID:       6ae0ac95-aead-462f-a6bd-edd48c8c32a6
:END:

* When Masters say their pupils have learned enough

I have a symbolical picture of the Master saying "I don't have
anything to teach you anymore.", as the the pupil have learned
enough. But, what does enough translates to?

Every master will leave a generative algorithm in the pupil's nervous
system. e.i., if the pupils follows the exact same path of the master,
he can become or go beyond the master's maestry. This means that
enough should not be understood as "your skills equates to
mine".

Since a Master of something have spent a lifetime on that
subject, he does not expect his pupil to master the art as he do. But,
instead, he sees the germin of the full pontential of the pupil down
that path.

From this point onwards, the level of mastery of the student becomes
the result of the path he takes.

* The effect of many Masters

From the linear combination of this nervous system change of the
pupil, conjuct to his unique path, becomes what he is.
