#+title: Wiedemann-Franz Law - Lorenz Number
- tags :: [[file:20210628041325-insulator_materials.org][Insulator (Materials)]]. [[file:20210628041351-insulator_people.org][Insulator (People)]]. [[file:20210628041652-thermal_conductivity.org][Thermal Conductivity]]. [[file:20210628041942-metals.org][Metals]]. 

* What does it explains and when does it is obeyed 

#+begin_quote
At a given temperature, the thermal and electrical conductivities of metals are proportional, but raising the temperature increases the thermal conductivity while decreasing the electrical conductivity. This behavior is quantified in the Wiedemann–Franz law. This law states that the ratio of the electronic contribution of the thermal conductivity (k) to the electrical conductivity (σ) of a metal is proportional to the temperature (T). ([[https://www.nuclear-power.net/nuclear-engineering/heat-transfer/thermal-conduction/thermal-conductivity/wiedemann-franz-law-lorenz-number/][Nuclear Power for Everybody website]], 2021)
#+end_quote

#+begin_quote
Highly electrically conductive silver is less thermally conductive than diamond, which is an electrical insulator but conducts heat via phonons due to its orderly array of atoms. ([[https://en.wikipedia.org/wiki/Thermal_conductivity][Wikipedia website]], 2021)
#+end_quote

* Trace the parallel on Electrical (orderly) conduction and Thermal (chaotic/kinetic) conduction on People's behavior

- Tropical theory on behavior -> Nietzsche Ecce Homo.
- Trace explanations and observations on upper/lower and middle tropics. 
